import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Home from './page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark flex flex-col min-h-screen">
      <body className={`${inter.className} flex flex-col min-h-screen bg-gray-900 text-gray-100`}>
        <header className="bg-gray-800 text-white p-4">
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="hover:underline">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/dashboard" className="hover:underline">
                  Dashboard
                </Link>
              </li>
              <li>
                <Link href="/about" className="hover:underline">
                  About
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-1 p-8">{children}</main>
        <footer className="bg-gray-800 text-white text-center p-4">
          <p>© 2024 Your Website</p>
        </footer>
      </body>
    </html>
  );
}
